---
- hosts: localhost
  vars:
    region: us-east-1
    group_name: ec2_server_group
    instance_type: t2.micro 
    aws_access_key: xxxxxxxxxxxxx
    aws_secret_key: yyyyyyyyyyyyy
    image_id: ami-b63769a1
    number_of_instances: 1

  tasks:   
    - name: create ec2 key
      ec2_key:
         name: my_key
         state: present
         region: "{{ region }}"

    - name: Create group
      ec2_group: 
         name: "{{ group_name }}"
         description: test group
         region: "{{ region }}"
         state: present
         rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
         rules_egress: 
          - proto: all
            cidr_ip: 0.0.0.0/0  
        
    - name: create ec2 instances
      ec2:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         key_name: my_key
         group: "{{ group_name }}"
         region: "{{ region }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image_id }}"
         wait: true
         wait_timeout: 500
         count: "{{ number_of_instances }}"
      register: ec2_out

    - debug: var=ec2_out
    - debug: var=ec2_out.instances.public_dns_name

#    - name: Wait for the instaces to be up
#      wait_for: host="{{ item.instances.public_dns_name }}" port=22 delay=60 timeout=230 state=started
#      with_items: '"{{ ec2_out }}"'