---
    - name: create ec2 key
      ec2_key:
         name: my_key
         state: present
         region: "{{ region }}"
      register: ec2_key

    - name: save private key
      copy: content="{{ ec2_key.key.private_key }}" dest="keys/my_key.pem" mode=0600
      when: ec2_key.changed

    - name: Set authorized key from file
      shell: ssh-add keys/my_key.pem
      
    - name: Create group
      ec2_group: 
         name: "{{ group_name }}"
         description: test group
         region: "{{ region }}"
         state: present
         rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
         rules_egress: 
          - proto: all
            cidr_ip: 0.0.0.0/0  
        
    - name: create ec2 instances
      ec2:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         key_name: my_key
         group: "{{ group_name }}"
         region: "{{ region }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image_id }}"
         wait: true
         wait_timeout: 500
         count: "{{ number_of_instances }}"
         instance_tags:
             Name: "{{ instance_tag }}"
      register: ec2

    - name: Waiting for the instance to come online
      local_action: wait_for
                    host={{ item.public_ip }}
                    state=started
                    port=22
      with_items: ec2.instances


    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: "{{ ec2.instances }}"
