---
- hosts: localhost
  vars:
    region: us-east-1
    group_name: wordPress_group
    instance_type: t2.micro 
    aws_access_key: 
    aws_secret_key: 
    image_id: ami-b33e8ca5
    number_of_instances: 1

  tasks:   
    - name: create ec2 key
      ec2_key:
         name: my_key
         state: present
         region: "{{ region }}"
      register: ec2_key

    - name: save private key
      copy: content="{{ ec2_key.key.private_key }}" dest="keys/my_key.pem" mode=0600
      when: ec2_key.changed

    - name: Create group
      ec2_group: 
         name: "{{ group_name }}"
         description: test group
         region: "{{ region }}"
         state: present
         rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 7189
            to_port: 7189
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 7180
            to_port: 7180
            cidr_ip: 0.0.0.0/0
         rules_egress: 
          - proto: all
            cidr_ip: 0.0.0.0/0  
        
    - name: create ec2 instances
      ec2:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         key_name: my_key
         group: "{{ group_name }}"
         region: "{{ region }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image_id }}"
         wait: true
         wait_timeout: 500
         count: "{{ number_of_instances }}"
         instance_tags:
             Name: ec2s
      register: ec2

    - debug: var=ec2.instance_ids

    - debug: var=item.public_ip
      with_items: ec2.instances

    - name: Wait for the instaces to be up
      wait_for: host=item.public_ip port=22 delay=60 timeout=230 state=started
      with_items: ec2.instances

#    - copy:
#        src: install_director.sh
#        dest: /tmp/install_director.sh
